### ISSUE TITLE
Add vertical ground motion parameters ...

### ISSUE THREAD

**Issue by nluco-usgs** [usgs/earthquake-design-ws#153] opened 2017-08-16 20:04 UTC
... C_v (Table 11.9-1); S_aMv (Eqs. 11-9-1 through 11.9-4) - Vertical MCE spectrum; S_av (Section 11.9.3) - Vertical design spectrum (S_av = 2/3 x S_aMv).

**Comment by jdbrown-USGS** [comment] 2017-09-11 21:22
- duplicate of #230

**Closed by jdbrown-USGS** 2017-09-11 21:22 UTC
Labels: duplicate
